deps: fix cares link error with glibc < 2.17
Similar to commit 3f3a71e61e90d45293704f21c98bc0ea53bb09ff

`ares__timeval.c` uses `clock_gettime()` on Linux, and the symbol must
be resolved in `librt` prior to `glibc` 2.17:

> undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
> /lib64/librt.so.1: error adding symbols: DSO missing from command line